set( gca                       , ...
     'FontSize'   , 20 , ...
     'FontName'   , 'Helvetica' );
set(ftitle, ...
     'FontName'   , 'AvantGarde');
set( ftitle                    , ...
     'FontSize'   , 20          , ...
     'FontWeight' , 'bold',...      
     'Fontname'   , 'Courier');

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'YGrid'       , 'on'     , ...
  'XGrid'       , 'on'     , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'XTickLabel'  , [],...
  'YTickLabel'  , [],...
  'LineWidth'   , 1         );


%  'XMinorTick'  , 'on'      , ...
%  'YMinorTick'  , 'on'      , ...