% BDP_autoplot creates figures to compare within a time range
hold on;
for qq=1:numel(pseries)
    eval(['plot(' char(xseries)  ',' char(pseries(qq)) '(pindex),''LineWidth'',Width' num2str(qq) ',''Color'',DataColor' num2str(qq) ',''Marker'',Marker' num2str(qq) ',''MarkerSize'',MkS' num2str(qq) ');']) 
end


hold off
grid on;

set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hTitle, hXLabel, hYLabel, hText], ...
    'FontName'   , 'AvantGarde');
set([hLegend, gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel, hText]  , ...
    'FontSize'   , 10          );
set( hTitle                    , ...
    'FontSize'   , 12          , ...
    'FontWeight' , 'bold'      );

set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
  'YTick'       , 0:500:2500, ...
  'LineWidth'   , 1         );